#TotalCpu on local machine: 10000m
#TotalMemory on local machine: 16000Mi
#Each KIND node on creation has 10 cores and 8GB of memory allocatable by default.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
