apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdapt-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdapt-scheduler
  template:
    metadata:
      labels:
        app: kdapt-scheduler
    spec:
      serviceAccountName: kdapt-scheduler
      containers:
        - name: scheduler
          image: kvv1618/kdapt-scheduler:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/kube-scheduler
            - --config=/config/scheduler-config.yaml
            - --leader-elect=false
