apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdapt-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdapt-scheduler-role
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/status
    - pods/binding
    - nodes
    - nodes/status
    - namespaces
    - events
    - bindings
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - create
- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs:
    - get
    - watch
    - list
    - update
    - create
- apiGroups: ["apps"]
  resources:
    - replicasets
    - statefulsets
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdapt-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdapt-scheduler-role
subjects:
- kind: ServiceAccount
  name: kdapt-scheduler
  namespace: kube-system
