apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdapt-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdapt-scheduler-role
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/status
    - pods/binding
    - nodes
    - nodes/status
    - namespaces
    - events
    - bindings
    - configmaps
    - services
    - persistentvolumeclaims
    - persistentvolumes
    - secrets
    - replicationcontrollers
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - create
- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs:
    - get
    - watch
    - list
    - update
    - create
- apiGroups: ["apps"]
  resources:
    - replicasets
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups: ["resource.k8s.io"]
  resources:
    - deviceclasses
    - resourceslices
    - resourceclaims
    - resourceclaims/status
    - resourceclaimtemplates
    - devicetaintrules
    - workloads
  verbs:
    - get
    - list
    - watch
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs:
    - get
    - list
    - watch
- apiGroups: ["storage.k8s.io"]
  resources:
    - csistoragecapacities
    - storageclasses
    - volumeattachments
    - csinodes
    - csidrivers
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdapt-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdapt-scheduler-role
subjects:
- kind: ServiceAccount
  name: kdapt-scheduler
  namespace: kube-system
